# Etapa de desarrollo
FROM node:20-alpine

# Crear directorio de trabajo
WORKDIR /app

# Copiar dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código fuente
COPY . .

# Exponer el puerto de desarrollo
EXPOSE 8080

# Comando para modo dev
CMD ["npm", "run", "dev", "--", "--host", "--port", "8080"]
